name: arb_poc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.13
  flutter_i18n: ^0.36.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: 5.4.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true